

import Constants from "expo-constants";
const STATUS_BAR_HEIGHT = Constants.statusBarHeight

import { listsHorizontalProximity } from "../../../app_values/AppDefault";
import { Dimensions } from "react-native";

const SCREEN_PROXIMYTY_HRZ = listsHorizontalProximity['true']

const { height: DEVICE_H, width: DEVICE_W } = Dimensions.get('window');

const OS_NAVIGATION_BAR_HEIGHT = Dimensions.get('screen').height - (Dimensions.get('window').height + Constants.statusBarHeight)


const STYCKYS_HEIGHT = 33
const HEADER_TOOL_HEIGHT = 50
const SECTIONS_SELECTOR_HEIGHT = 46
const PRIMARY_HEADER_HEIGHT = STATUS_BAR_HEIGHT+HEADER_TOOL_HEIGHT
const SECONDARY_HEADER_HEIGHT = PRIMARY_HEADER_HEIGHT + SECTIONS_SELECTOR_HEIGHT

const MARGIN_BOBBER = 8

const TRANSPARENT_COLOR = '#00000000'

const LIST_ITEM_SIZE = {
    h: DEVICE_W/2 + 1,
    w: DEVICE_W/2 + 1
}
const HEAD_COMPONENT_HEIGHT = LIST_ITEM_SIZE.h + 20

export default {
    OS_NAVIGATION_BAR_HEIGHT: OS_NAVIGATION_BAR_HEIGHT,

    SCREEN_PROXIMYTY_HRZ: SCREEN_PROXIMYTY_HRZ,

    STYCKYS_HEIGHT: STYCKYS_HEIGHT,
    HEADER_TOOL_HEIGHT: HEADER_TOOL_HEIGHT,
    SECTIONS_SELECTOR_HEIGHT: SECTIONS_SELECTOR_HEIGHT,
    PRIMARY_HEADER_HEIGHT: PRIMARY_HEADER_HEIGHT,
    SECONDARY_HEADER_HEIGHT: SECONDARY_HEADER_HEIGHT,

    HEAD_COMPONENT_HEIGHT: HEAD_COMPONENT_HEIGHT,
    LIST_ITEM_SIZE: LIST_ITEM_SIZE,

    MARGIN_BOBBER:  MARGIN_BOBBER,

    TRANSPARENT_COLOR: TRANSPARENT_COLOR
}
